version: "3.8"
services:
  chatbot:
    build: .
    ports:
      - "8000:8000"
    environment:
      - EVOLUTION_API_URL=http://evolution-api:8080
    depends_on:
      - evolution-api
  evolution-api:
    image: "evoapicloud/evolution-api:v1.8.7"