# fly.toml para o chatbot-python-lucas
app = 'chatbot-python-lucas'
primary_region = 'gru'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = "15s"
    timeout = "10s"
    grace_period = "30s"
    method = "get"
    path = "/"

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  PYTHONUNBUFFERED = "1"